apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hivebox

  template:
    metadata:
      labels:
        app: hivebox

    spec:
      containers:
        - name: hivebox

          image: moeelnady/hivebox:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8080